name: Java Build
permissions: {}

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]

  schedule:
    # daily at 1:30 UTC
    - cron:  '30 1 * * *'
    
concurrency:
  group: java-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        java: [ "11", "17" ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build JAR Artifacts and verify coverage
        run: mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean package -Drevision=$(git describe --tags --always)
      - name: Upload Artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: maven-build-java-${{ matrix.java }}
          path: target/
          if-no-files-found: error
          retention-days: 5
