name: Java Build
permissions: {}

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]

  schedule:
    # daily at 1:30 UTC
    - cron:  '30 1 * * *'
    
concurrency:
  group: java-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        java: [ "11", "17" ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build JAR Artifacts and verify coverage
        run: mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean package -Drevision=$(git describe --tags --always)
      - name: Upload Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: maven-build-java-${{ matrix.java }}
          path: target/
          if-no-files-found: error
          retention-days: 5
