name: Conventional Commits
permissions: {}

on:
  pull_request:
    branches: ["main", "release-*"]

concurrency:
  group: commit-lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commits:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: ["20"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: ${{ matrix.node }}
      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Verify conventional commits
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
