name: Conventional Commits
permissions: {}

on:
  pull_request:
    branches: ["main", "release-*"]

concurrency:
  group: commit-lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commits:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: ["20"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: ${{ matrix.node }}
      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Verify conventional commits
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
