name: Conventional Commits
permissions: {}

on:
  pull_request:
    branches: ["main", "release-*"]
  merge_group:

concurrency:
  group: commit-lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commits:
    # dependabot won't conform with commits, keep CI checks green by ignoring this soft-check
    if: ${{ !contains(github.actor, 'dependabot') }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: ["20"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: ${{ matrix.node }}
      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Verify conventional commits
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
