name: Java E2E
permissions: {}

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]
  merge_group:

  schedule:
    # daily at 2:30 UTC
    - cron: "30 2 * * *"

concurrency:
  group: java-e2e-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1

jobs:
  e2e-apache:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: ["17"]
        kafka: ["3.9.0","4.0.0"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      KAFKA_VERSION: ${{ matrix.kafka }}
      COMPOSE_FILE: "e2e/docker_compose.yaml"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: Run Kafka Connect ${{ matrix.kafka }} E2E Tests with Apache Kafka
        run: |
          echo "Running integration tests with Docker Compose file: ${COMPOSE_FILE}"
          docker compose -f ${COMPOSE_FILE} pull
          mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean verify -Drevision=$(git describe --tags --always)

  e2e-confluent:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: ["17"]
        kafka: ["7.9.0"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      COMPOSE_FILE: "e2e/docker_compose_confluent.yaml"
      KAFKA_VERSION: ${{ matrix.kafka }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: Run Confluent Kafka Platform ${{ matrix.kafka }} E2E Tests
        run: |
          echo "Running integration tests with Docker Compose file: ${COMPOSE_FILE}"
          docker compose -f ${COMPOSE_FILE} pull
          mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean verify -Drevision=$(git describe --tags --always)

  e2e-redpanda:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: ["17"]
        kafka: ["3.9.0","4.0.0"]
        redpanda: ["v24.2.21"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      KAFKA_VERSION: ${{ matrix.kafka }}
      REDPANDA_VERSION: ${{ matrix.redpanda }}
      COMPOSE_FILE: "e2e/docker_compose_redpanda.yaml"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: Run Kafka Connect ${{ matrix.kafka }} E2E Tests with Redpanda ${{ matrix.redpanda }}
        run: |
          echo "Running integration tests with Docker Compose file: ${COMPOSE_FILE}"
          docker compose -f ${COMPOSE_FILE} pull
          mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean verify -Drevision=$(git describe --tags --always)
