name: Java E2E
permissions: {}

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]

  schedule:
    # daily at 2:30 UTC
    - cron: "30 2 * * *"

concurrency:
  group: java-e2e-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: ["11", "17"]
        kafka: ["3.5.1","3.6.0"]
        broker: ["kafka","redpanda"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      KAFKA_VERSION: ${{ matrix.kafka }}
      COMPOSE_FILE: "e2e/docker_compose.yaml"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: Run Kafka Connect ${{ matrix.kafka }} E2E Tests with ${{ matrix.broker }}
        run: |
          if [[ ${{ matrix.broker }} == "redpanda" ]]; then 
            export COMPOSE_FILE=e2e/docker_compose_redpanda.yaml
          fi
          echo "Running integration tests with Docker Compose file: ${COMPOSE_FILE}"
          mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean verify -Drevision=$(git describe --tags --always)
  # special treatment due to different versioning scheme
  e2e-confluent:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: ["11", "17"]
        kafka: ["7.4.2","7.5.1"]
        broker: ["confluent"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      COMPOSE_FILE: "e2e/docker_compose_confluent.yaml"
      KAFKA_VERSION: ${{ matrix.kafka }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: Run ${{ matrix.broker }} Platform ${{ matrix.kafka }} E2E Tests
        run: |
          echo "Running integration tests with Docker Compose file: ${COMPOSE_FILE}"
          mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean verify -Drevision=$(git describe --tags --always)