name: Java E2E
permissions: {}

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]

  schedule:
    # daily at 2:30 UTC
    - cron: "30 2 * * *"

concurrency:
  group: java-e2e-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: ["11", "17"]
        kafka: ["3.4.0","3.4.1"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      KAFKA_TOPIC: eventbridge-e2e
      KAFKA_VERSION: ${{ matrix.kafka }}
      BOOTSTRAP_SERVER: kafka:29092
      EVENT: '"{\"testMessage\":\"eventbridge-e2e\"}"'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: Run Kafka ${{ matrix.kafka }} E2E Tests
        run: mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean verify -Drevision=$(git describe --tags --always)
