name: Java Code Format
permissions: {}

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]

concurrency:
  group: java-format-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        java: [ "11" ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Verify code format with Maven
        run: mvn --batch-mode --no-transfer-progress --errors com.spotify.fmt:fmt-maven-plugin:check
      - name: Verify licenses with Maven
        run: mvn --batch-mode --no-transfer-progress --errors  license:check