name: Java Code Format
permissions: {}

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]
  merge_group:

concurrency:
  group: java-format-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        java: [ "11" ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Verify code format with Maven
        run: mvn --batch-mode --no-transfer-progress --errors -Drevision=0.0.0 com.spotify.fmt:fmt-maven-plugin:check
      - name: Verify licenses with Maven
        run: mvn --batch-mode --no-transfer-progress --errors  -Drevision=0.0.0 license:check