name: git-secrets Check
permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  git-secrets:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          repository: awslabs/git-secrets
          ref: master
          path: git-secrets
      - name: Install git-secrets
        run: |
          pushd git-secrets
          sudo make install
          popd
      - name: Run git-secrets
        run: |
          git-secrets --register-aws
          # If no files are provided, all files returned by git ls-files are scanned
          git-secrets --scan
