name: git-secrets Check
permissions: {}

on:
  push:
  workflow_dispatch:

jobs:
  git-secrets:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          repository: awslabs/git-secrets
          ref: master
          path: git-secrets
      - name: Install git-secrets
        run: |
          pushd git-secrets
          sudo make install
          popd
      - name: Run git-secrets
        run: |
          git-secrets --register-aws
          # If no files are provided, all files returned by git ls-files are scanned
          git-secrets --scan
