name: git-secrets Check
permissions: {}

on:
  push:
  workflow_dispatch:

jobs:
  git-secrets:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: awslabs/git-secrets
          ref: master
          path: git-secrets
      - name: Install git-secrets
        run: |
          pushd git-secrets
          sudo make install
          popd
      - name: Run git-secrets
        run: |
          git-secrets --register-aws
          # If no files are provided, all files returned by git ls-files are scanned
          git-secrets --scan
