name: git-secrets Check
permissions: {}

on:
  push:
  workflow_dispatch:

  pull_request:
    branches: ["main", "release-*"]
  merge_group:

jobs:
  git-secrets:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          repository: awslabs/git-secrets
          ref: master
          path: git-secrets
      - name: Install git-secrets
        run: |
          pushd git-secrets
          sudo make install
          popd
      - name: Run git-secrets
        run: |
          git-secrets --register-aws
          # If no files are provided, all files returned by git ls-files are scanned
          git-secrets --scan
